//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Packages/nl.jessestam.tower-defence/Input/DebugActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace TowerDefence.Input
{
    public partial class @DebugActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @DebugActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""DebugActions"",
    ""maps"": [
        {
            ""name"": ""Waves"",
            ""id"": ""e2bfb0c6-5377-4fed-b9d3-352c085be677"",
            ""actions"": [
                {
                    ""name"": ""StartWaves"",
                    ""type"": ""Button"",
                    ""id"": ""feb32389-1b27-4f88-8738-715af39689c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a6006c80-a126-4c66-9cce-972512c946bb"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartWaves"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Waves
            m_Waves = asset.FindActionMap("Waves", throwIfNotFound: true);
            m_Waves_StartWaves = m_Waves.FindAction("StartWaves", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Waves
        private readonly InputActionMap m_Waves;
        private IWavesActions m_WavesActionsCallbackInterface;
        private readonly InputAction m_Waves_StartWaves;
        public struct WavesActions
        {
            private @DebugActions m_Wrapper;
            public WavesActions(@DebugActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @StartWaves => m_Wrapper.m_Waves_StartWaves;
            public InputActionMap Get() { return m_Wrapper.m_Waves; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(WavesActions set) { return set.Get(); }
            public void SetCallbacks(IWavesActions instance)
            {
                if (m_Wrapper.m_WavesActionsCallbackInterface != null)
                {
                    @StartWaves.started -= m_Wrapper.m_WavesActionsCallbackInterface.OnStartWaves;
                    @StartWaves.performed -= m_Wrapper.m_WavesActionsCallbackInterface.OnStartWaves;
                    @StartWaves.canceled -= m_Wrapper.m_WavesActionsCallbackInterface.OnStartWaves;
                }
                m_Wrapper.m_WavesActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @StartWaves.started += instance.OnStartWaves;
                    @StartWaves.performed += instance.OnStartWaves;
                    @StartWaves.canceled += instance.OnStartWaves;
                }
            }
        }
        public WavesActions @Waves => new WavesActions(this);
        public interface IWavesActions
        {
            void OnStartWaves(InputAction.CallbackContext context);
        }
    }
}
